spring:  
  cloud:
    gateway:
      routes:
        - id : PROVIDER-SERVICE
          uri : lb://PROVIDER-SERVICE
          predicates :
            - Path= /providers/**
            
        - id : ARTICLE-SERVICE
          uri : lb://ARTICLE-SERVICE
          predicates :
            - Path= /articles/**
